config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for(
    :admin_users,
    controllers: {
      registrations: 'admin_user_registrations',
      sessions: 'admin_user_sessions'
    }
  )

  devise_scope :admin_user do
    # root to: "admin_user_registrations#new"
    root to: "dashboard#show"
  end

  resources :task_queues, only: %i[new index show create edit update] do
    member do
      post 'outcome'
      get 'record'
      get 'preview'
      get 'field_settings'
    end

    # get 'table_fields_with_type'
  end

  resources :tables, only: %i[index show]
  get 'tables/:table_name/:record_id', to: 'tables#preview', as: 'table_record_preview'
  get 'table/settings', to: 'tables#settings'
  post 'table/update_settings', to: 'tables#update_settings'
  get 'table/add_record', to: 'tables#add_record'
  get 'table/edit_record', to: 'tables#edit_record'
  post 'table/update_record', to: 'tables#update_record'
  post 'table/create_record', to: 'tables#create_record'
  post 'table/delete_record', to: 'tables#delete_record'

  patch 'table_field', to: 'tables#update_table_field', as: 'update_table_field'
  patch 'related_table_field', to: 'tables#update_related_table_field', as: 'update_related_table_field'

  # get 'layouts/table_fields_with_type', to: 'layout_builder#table_fields_with_type'
  resources :layout_builder, as: "layouts", path: 'layouts'
  get 'layouts/:id/preview', to: 'layout_builder#preview', as: 'layout_builder_preview'
  patch 'layouts/:id/related_tables', to: 'layout_builder#update_related_tables', as: 'update_related_tables'
  patch 'layouts/:id/related_tables/remove', to: 'layout_builder#remove_related_table', as: 'remove_related_table'

  # get 'view_builder/table_fields', to: 'view_builder#table_fields'
  # # get 'view_builder/view', to: 'view_builder#view_page'
  # get 'view_builder/retrieve_data', to: 'view_builder#retrieve_data'

  get 'users/edit', to: 'admin_users#edit'
  get 'users/:id', to: 'admin_users#show_modal'
  post 'admin_users/update_role', to: 'admin_users#update_role'
  post 'admin_users/update_status', to: 'admin_users#update_status'
  post 'admin_users/create_new', to: 'admin_users#create_new'
  patch 'admin_users/create_new', to: 'admin_users#update'
  delete 'users', to: 'admin_users#destroy'
  get 'users', to: 'admin_users#index'

  resources :databases
  get 'table_fields_with_type', to: 'databases#table_fields_with_type'
  get 'related_table_fields_with_type', to: 'databases#related_table_fields_with_type'


  # resources :view_builder
  resources :activities, only: %i[create index]
  post 'activities/create_js', to: 'activities#create_js'

  resources :organisation_settings, only: %i[edit update]
  resources :admin_users, only: %i[new]
  resources :permissions, only: :index

  post 'permissions/add_to_role', to: 'permissions#add_to_role', as: 'add_to_role'
  post 'permissions/remove_from_role', to: 'permissions#remove_from_role'
  post 'permissions/enable_all', to: 'permissions#enable_all'
  post 'permissions/disable_all', to: 'permissions#disable_all'

  resource :roles, only: %i[edit update]

  get 'dashboard', to: 'dashboard#show'
  post 'add-sql-filter', to: 'work_lists#add_sql_filter'
  post 'remove-sql-filter', to: 'work_lists#remove_sql_filter'
  post 'remove-work-list-outcome', to: 'work_lists#remove_work_list_outcome'
  post 'add-work-list-outcome', to: 'work_lists#add_work_list_outcome'

  post 'token/generate' => 'token#generate'
  post 'call/connect' => 'call#connect'

  get 'license', to: 'dashboard#license'
  post 'license/verify', to: 'dashboard#verify_license'
  get 'license/verify', to: 'dashboard#verify_license', as: 'verify_license'

  get 'data_table_states/load'
  post 'data_table_states/save'

  match "database_connection_error", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match '/404' => 'errors#not_found', via: :all
  match '/406' => 'errors#not_acceptable', via: :all
  match '/401' => "errors#not_authorized", via: :all
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_admin_user!, except: %i[license verify_license]
  before_action :load_admin_db_config,
                :load_task_queues
                # :check_license, only: [:show]
  before_action :set_databases

  layout 'license', only: %i[license verify_license]

  def show
    full_license = OrganisationSetting.last.full_license
    @trial_license = !full_license
    @activities_for_user = Activity.where(
      user_id: current_admin_user.id
    ).sort_by(&:created_at).reverse[0..4]
  end

  def license
    # Temporarily removing licensing
    # redirect_to dashboard_path if license_valid?
    redirect_to dashboard_path
  end

  def verify_license
    license_key = params[:license_key]
    license_valid = activate_license(license_key)

    if license_valid && AdminUser.count.zero?
      save_license(license_key: license_key, full_license: false)
      redirect_to new_admin_user_registration_path
    elsif license_valid
      save_license(license_key: license_key, full_license: false)
      redirect_to admin_user_registration_path
    else
      render 'verify_license'
    end
  end

  private

  def set_databases
    @databases = Database.all.sort
  end

  def save_license(license_key:, full_license:)
    OrganisationSetting.create!(
      license_key: license_key,
      full_license: full_license
    )
  end

  def load_admin_db_config
    db = Rails.configuration.database_configuration[Rails.env]
    @admin_database = OpenStruct.new
    @admin_database.username = db['username']
    @admin_database.database = db['database']
    @admin_database.password = db['password']
    @admin_database.host = db['host']
    @admin_database.type = db['adapter']
    @admin_database.port = db['port']
  end
end

app/views/dashboard/_license_form.html.erb
<%= form_tag("/license/verify", method: "post") do %>
  <div class="form-group">
    <%= label_tag(:license_key, "License key") %>
    <%= text_field_tag(:license_key, '', {class: 'form-control', required: true}) %>
  </div>

  <p>
    If this was a trial license you will need to <a href="https://missionkontrol.io/register/"  target="_blank">buy a license here</a>.
  </p>

  <%= submit_tag("Submit", {class: 'btn btn-primary'}) %>
<% end %>

app/views/dashboard/license.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 m-t-xl m-b-xl">
      <div class="ibox margin-bottom">
        <div class="ibox-content">
          <div class="text-center">
            <div class="logo-wrapper">
              <a href="/">
                <img src="/assets/logos/MissionKontrol-logo-original.png" alt="">
              </a>
            </div>
          </div>

          <h2>Welcome</h2>

          <hr>

          <p>Welcome to the installation process. You’ll need a license key to get set-up. You can get a trial or full license key from <a href="https://www.missionkontrol.io">www.missionkontrol.io</a></p>

          <%= render 'license_form' %>

          <p class="hide">
            <b>Server response:</b> License terminated. If this is unexpected please contact team@missionkontrol.io
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="row wrapper page-heading dashboard--title">
  <h1 class="bold">Welcome to MissionKontrol</h1>
  <h4><%= Time.now.strftime("%A %d %B %Y") %></h4>
</div>

<div class="row wrapper m-t p-h-xs">
  <div class="col-sm-8">
    <div class="row">
      <%
=begin%>
 <% if @trial_license %>
        <div class="col-sm-12">
          <div class="dashboard--trial-license">
            <h1>You're on a trial license</h1>
            <h5>Let us know if there is anything we can help with. Subscribe Now.</h5>
          </div>
        </div>
      <% end %> 
<%
=end%>
      <div class="col-sm-12 dashboard--panels">
        <div class="row">
          <div class="col-sm-4">
            <div class="dashboard--panel" data-link="<%= new_database_path if current_admin_user.admin_abilities? %>">
              <img src="/assets/images/icons/database-2.png">
              <h3>Connect a database</h3>
              <h5>Add a database to get started building your admin interface</h5>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="dashboard--panel" data-link="<%= permissions_path if current_admin_user.admin_abilities? %>">
              <img src="/assets/images/icons/report.png">
              <h3>Configure tables</h3>
              <h5>Once you have connected a database set-up some tables</h5>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="dashboard--panel" data-link="<%= users_path if current_admin_user.admin_abilities? %>">
              <img src="/assets/images/icons/team-1.png">
              <h3>Invite users</h3>
              <h5>Set permissions and add some users</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-4 border-left">
    <div class="border-bottom">
      <h2>System</h2>
    </div>
    <div class="dashboard--system">
      <ul>
        <li>
          <a href="https://missionkontrol.io/documentation/changelog/" target="_blank">Current version: v0.2.2</a>
        </li>

        <li>
           <a href="https://missionkontrol.io/documentation/" target="_blank">Documentation</a>
        </li>

        <li>
          <a href="https://missionkontrol.io" target="_blank">Official homepage</a>
        </li>

        <li>
          <a href="https://missionkontrol.io/documentation/changelog/" target="_blank">List of changes</a>
        </li>

        <li>
          <a href="https://missionkontrol.io/contact-us/ target="_blank"">Request a feature</a>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 light-grey-bg">
    <div class="tabs-container">
      <div class="tab-content">
        <div id="tab-1" class="tab-pane active all-activities-tab">
          <div class="panel-body">
            <h2>Activity history</h2>
            <div class="activity-stream">
              <% if @activities_for_user %>
                <%= render 'shared/activity_stream', activities: @activities_for_user, locals: { hide: false, link: true } %>
              <% else %>
                <p class="default-message">You haven't recorded any activity yet.</p>
                <%= render 'shared/activity_stream', activities: @activities_for_user, locals: { hide: true, link: true } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/verify_license.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 m-t-xl m-b-xl">
      <div class="ibox margin-bottom">
        <div class="ibox-content">
          <div class="text-center">
            <div class="logo-wrapper">
              <a href="/">
                <img src="/assets/logos/MissionKontrol-logo-original.png" alt="">
              </a>
            </div>
          </div>

          <h2>License invalid</h2>

          <hr>

          <p>You’ll need a valid license key to continue. If this is unexpected please contact team@missionkontrol.io</p>

          <%= render 'license_form' %>
        </div>
      </div>
    </div>
  </div>
</div>