config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for(
    :admin_users,
    controllers: {
      registrations: 'admin_user_registrations',
      sessions: 'admin_user_sessions'
    }
  )

  devise_scope :admin_user do
    # root to: "admin_user_registrations#new"
    root to: "dashboard#show"
  end

  resources :task_queues, only: %i[new index show create edit update] do
    member do
      post 'outcome'
      get 'record'
      get 'preview'
      get 'field_settings'
    end

    # get 'table_fields_with_type'
  end

  resources :tables, only: %i[index show]
  get 'tables/:table_name/:record_id', to: 'tables#preview', as: 'table_record_preview'
  get 'table/settings', to: 'tables#settings'
  post 'table/update_settings', to: 'tables#update_settings'
  get 'table/add_record', to: 'tables#add_record'
  get 'table/edit_record', to: 'tables#edit_record'
  post 'table/update_record', to: 'tables#update_record'
  post 'table/create_record', to: 'tables#create_record'
  post 'table/delete_record', to: 'tables#delete_record'

  patch 'table_field', to: 'tables#update_table_field', as: 'update_table_field'
  patch 'related_table_field', to: 'tables#update_related_table_field', as: 'update_related_table_field'

  # get 'layouts/table_fields_with_type', to: 'layout_builder#table_fields_with_type'
  resources :layout_builder, as: "layouts", path: 'layouts'
  get 'layouts/:id/preview', to: 'layout_builder#preview', as: 'layout_builder_preview'
  patch 'layouts/:id/related_tables', to: 'layout_builder#update_related_tables', as: 'update_related_tables'
  patch 'layouts/:id/related_tables/remove', to: 'layout_builder#remove_related_table', as: 'remove_related_table'

  # get 'view_builder/table_fields', to: 'view_builder#table_fields'
  # # get 'view_builder/view', to: 'view_builder#view_page'
  # get 'view_builder/retrieve_data', to: 'view_builder#retrieve_data'

  get 'users/edit', to: 'admin_users#edit'
  get 'users/:id', to: 'admin_users#show_modal'
  post 'admin_users/update_role', to: 'admin_users#update_role'
  post 'admin_users/update_status', to: 'admin_users#update_status'
  post 'admin_users/create_new', to: 'admin_users#create_new'
  patch 'admin_users/create_new', to: 'admin_users#update'
  delete 'users', to: 'admin_users#destroy'
  get 'users', to: 'admin_users#index'

  resources :databases
  get 'table_fields_with_type', to: 'databases#table_fields_with_type'
  get 'related_table_fields_with_type', to: 'databases#related_table_fields_with_type'


  # resources :view_builder
  resources :activities, only: %i[create index]
  post 'activities/create_js', to: 'activities#create_js'

  resources :organisation_settings, only: %i[edit update]
  resources :admin_users, only: %i[new]
  resources :permissions, only: :index

  post 'permissions/add_to_role', to: 'permissions#add_to_role', as: 'add_to_role'
  post 'permissions/remove_from_role', to: 'permissions#remove_from_role'
  post 'permissions/enable_all', to: 'permissions#enable_all'
  post 'permissions/disable_all', to: 'permissions#disable_all'

  resource :roles, only: %i[edit update]

  get 'dashboard', to: 'dashboard#show'
  post 'add-sql-filter', to: 'work_lists#add_sql_filter'
  post 'remove-sql-filter', to: 'work_lists#remove_sql_filter'
  post 'remove-work-list-outcome', to: 'work_lists#remove_work_list_outcome'
  post 'add-work-list-outcome', to: 'work_lists#add_work_list_outcome'

  post 'token/generate' => 'token#generate'
  post 'call/connect' => 'call#connect'

  get 'license', to: 'dashboard#license'
  post 'license/verify', to: 'dashboard#verify_license'
  get 'license/verify', to: 'dashboard#verify_license', as: 'verify_license'

  get 'data_table_states/load'
  post 'data_table_states/save'

  match "database_connection_error", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match '/404' => 'errors#not_found', via: :all
  match '/406' => 'errors#not_acceptable', via: :all
  match '/401' => "errors#not_authorized", via: :all
end

app/models/task_queue.rb
# frozen_string_literal: true

class TaskQueue < ApplicationRecord
  validates :name, :table, presence: true
  has_many :task_queue_outcomes

  scope :enabled, -> { where(enabled: true) }

  def success_outcome_enabled?
    success_database_update['enabled'] ? true : false
  end

  def failure_outcome_enabled?
    failure_database_update['enabled'] ? true : false
  end
end

app/controllers/task_queues_controller.rb
# frozen_string_literal: true

class TaskQueuesController < ApplicationController
  include TaskQueueRender
  include TaskQueueRecordActivity
  include TableActivity
  include DatabasePresenterActions

  layout 'task_queue'
  before_action :set_database, only: %i[new create]
  before_action :set_activities, only: :edit

  def index
    @databases = Database.all
    @task_queues = TaskQueue.all
    render layout: 'standard'
  end

  def new
    database_connection
    @task_queue = TaskQueue.new
    @available_tables = available_tables
    @work_lists = WorkList.order(created_at: :desc)
  end

  def edit
    @task_queue = TaskQueue.find(params[:id])
    @database = Database.find(@task_queue.database_id)
    @database_connection = database_connection
    @target_db = target_db
    result = @target_db.all(@task_queue.table, 10, 0)
    @task_queue_sql = task_queue_to_sql
    @task_queue_headers = result.columns
    @table_fields = list_table_fields_with_type(@task_queue.table)
  end

  def create
    @task_queue = TaskQueue.new(task_queue_params)

    if @task_queue.save
      redirect_to edit_task_queue_path(@task_queue)
    else
      render 'create/error', status: 422, json: @task_queue.errors.full_messages
    end
  end

  def update
    @task_queue = TaskQueue.find(params[:id])
    update_task_queue
    @task_queue.save!
    @database = Database.find(@task_queue.database_id)
    @database_connection = database_connection
    data = data_for_preview(@task_queue)
    data.merge!(task_queue: @task_queue)
    render action: 'update/success', json: data
  rescue StandardError
    render action: 'update/error', status: 422, json: {}
  end

  def preview
    @task_queue = TaskQueue.find(params[:id])
    @database = Database.find(@task_queue.database_id)
    @database_connection = database_connection
    render_preview_js_task_queue
  end

  # TODO: this is duplicate of preview
  def show
    @task_queue = TaskQueue.find(params[:id])
    @database = Database.find(@task_queue.database_id)
    @database_connection = database_connection
    @target_db = target_db
    respond_to do |format|
      format.html do
        sql_result = @target_db.all(@task_queue.table, 10)
        @headers = sql_result ? sql_result.columns : []
        render layout: 'standard'
      end

      format.js do
        render_show_js_task_queue
      end
    end
  end

  def outcome
    task_queue = TaskQueue.find(outcome_params['task_queue_id'])
    outcome_success = outcome_params['outcome'] == 'success'

    item_timeout = outcome_success ? task_queue.success_outcome_timeout : task_queue.failure_outcome_timeout
    item_title = outcome_success ? task_queue.success_outcome_title : task_queue.failure_outcome_title

    outcome = create_outcome(outcome_params, item_timeout)

    @database = Database.find(task_queue.database_id)
    @database_connection = database_connection
    @target_db = target_db
    complete_outcome_actions(task_queue, outcome_params)

    ActiveRecord::Base.connection_pool.disconnect! if ActiveRecord::Base.connection_pool
    ActiveRecord::Base.establish_connection(ActiveRecord::Base.configurations.configs_for(env_name: Rails.env).first)

    render json: { outcome: outcome, user_id: current_admin_user.id, outcome_content: item_title }
  end

  def record
    @task_queue = TaskQueue.find(params[:id])
    @repo = Kuwinda::Repository::TargetDB.new(@task_queue.table)
    @row = params['task_queue_item_primary_key'].to_i
    set_activities_for_task_queue_record
    data = build_data_for_record
    render json: { row: data, activities: @activities_for_task_queue_record, author: current_admin_user.full_name }
  end

  def field_settings
    task_queue = TaskQueue.find(params[:id])
    render json: { fields: helpers.task_queue_draggable_field_settings_container(task_queue).values }
  end

  private

  def task_queue_params
    params.require(:task_queue).permit(:name,
                                       :details,
                                       :table,
                                       :database_id)
  end

  def task_queue_update_params
    params.require(:task_queue).permit(:name,
                                       :details,
                                       :query_builder_rules,
                                       :query_builder_sql,
                                       :raw_sql,
                                       :success_outcome_title,
                                       :success_outcome_timeout,
                                       :success_database,
                                       :failure_outcome_title,
                                       :failure_outcome_timeout,
                                       :failure_database,
                                       :enabled)
  end

  def outcome_params
    params.permit(:outcome, :task_queue_id, :table, :primary_key)
  end

  def handle_success(action:, js_func:, notice:)
    flash[:notice] = notice
    render(action: action, js: js_func)
  end

  def time_to_reappear?(row)
    outcome = TaskQueueOutcome.where(task_queue_id: @task_queue.id, task_queue_item_primary_key: row['id']).first

    return true unless outcome

    if outcome.task_queue_item_reapper_at && outcome.task_queue_item_reappear_at < Time.now
      outcome.delete
      true
    else
      false
    end
  end

  def field_visible?(task_queue, field)
    return task_queue.draggable_fields unless task_queue.draggable_fields.present?

    task_queue.draggable_fields.values.map { |f| f['title'] }.include?(field)
  end

  def build_data_for_record
    repo = Kuwinda::Repository::TargetDB.new
    repo.table = @task_queue.table
    row = repo.find(params['task_queue_item_primary_key'])
    record = {}
    row.each do |k, v|
      next unless field_visible?(@task_queue, k)

      record[k] = v
    end

    record
  end

  def set_database
    @database = Database.find(params[:database_id] || task_queue_params[:database_id])
  end
end

app/views/task_queues/_preview.html.erb
<br>
<h2 class="bold">Results</h2>
<br>
<div class="table-responsive no-overflow">
  <table id="task-queue-preview-table" class="table hide" data-paging="true"  data-table-name="<%= @task_queue.table %>" data-database-id="<%= @task_queue.database_id %>">
    <thead>
      <% if @task_queue_headers %>
        <tr>
          <% @task_queue_headers.each do |header|%>
            <th class='column-<%= header %>'><%= header.humanize %></th>
          <% end %>
        </tr>
      <% end %>
    </thead>

    <tbody></tbody>
  </table>
</div>

app/views/task_queues/_preview_show.html.erb
<div id="task-queue-preview-container">
    <div class="task-queue-preview-item">
      <div class="row min-height-100vh no-margin">
        <div class="col-sm-4 min-height-100vh">
          <div class="" style="">
            <br>
            <div class="" id="task-queue-field-settings-preview-container">
              <% task_queue_draggable_field_settings_container(@task_queue).each do |field| %>
                <p><b><%= field[1]["title"] %></b></p>
                <div class="divider"></div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="col-sm-8 gray-bg min-height-100vh">
          <br>
          <%= render 'shared/activity_history_template', feedable_type: 'task_queue', feedable_id: @task_queue.id %>
        </div>
      </div>
    </div>
</div>

app/views/task_queues/_task_queue_builder.html.erb
<div class="hide" id="database-id">
  <%= @database.id %>
</div>
<div class="row">
  <div class="col-sm-12">
    <br>
    <div id="builder" data-task-queue-table="<%= @task_queue.table %>" data-task-queue-id="<%= @task_queue.id %>" data-task-queue-rules="<%= @task_queue.query_builder_rules %>"></div>
    <br>
    <button type="button" name="button" class="btn btn-primary pull-right task-queue-update-button" id="task-queue-update-button">Update Query</button>
  </div>
</div>

app/views/task_queues/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'moment/moment.min.js' %>
  <%= javascript_include_tag 'dataTable/datatables.min.js' %>
  <%= javascript_include_tag 'query-builder/query-builder.min.js' %>
<% end %>

<div class="row" style="margin: 0">
  <div class="tab-content no-padding">
    <%= render 'task_queues/shared/task_queue_create_tab' %>
    <%= render 'task_queues/shared/task_queue_define_tab' %>
    <%= render 'task_queues/shared/task_queue_publish_tab' %>
  </div>
</div>

<div id="task-queue-item-modal" class="modal fade" aria-hidden="true" data-task-queue-id="<%= @task_queue.id %>">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body" style="padding: 0">
        <div class="row" style="background-color: #eaeaea;">
          <div class="col-sm-5 border-right" style="padding: 50px 25px">
            <h3 class="m-t-none m-b">
              <%= @task_queue.name %>
            </h3>

            <p>
              <%= @task_queue.details %>
            </p>

            <div id="task_queue_item_data">
            </div>

            <div class="text-center" style="margin-top: 20px">
              <% if @task_queue.success_outcome_title.present? && @task_queue.success_outcome_timeout.present? %>
                <a href="#" onclick="applyOutcomeRule('success')" class="btn btn-primary"><%= @task_queue.success_outcome_title %></a>
              <% end %>
            </div>

            <div class="text-center" style="margin-top: 20px">
              <% if @task_queue.failure_outcome_title.present? && @task_queue.failure_outcome_timeout.present? %>
                <a href="#" onclick="applyOutcomeRule('failure')" class="btn btn-default"><%= @task_queue.failure_outcome_title %></a>
              <% end %>
            </div>
          </div>

          <div class="col-sm-7" style="background-color: white;padding: 50px 25px;min-height: 500px">
            <%= render 'shared/activity_history_task_queue_item', feedable_type: @task_queue.table %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/task_queues/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-6">
    <h1>Available Task Queues</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to 'Home', dashboard_path %>
      </li>

      <li class="breadcrumb-item">
        <%= link_to 'Task Queues', task_queues_path %>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated ">
  <div class="row">
    <div class="col-sm-12">
      <% @databases.each do |database| %>
        <button class="accordion task-queues"><%= database.friendly_name %><span class="float-right"><img src="/assets/images/icons/plus-thick.png"></span></button>
        <div class="panel">
          <div class="col-sm-2 pull-right margin-top-nav">
            <%= link_to('Add new', new_task_queue_path(database_id: database.id), html_options = { class: "btn btn-purple" }) %>
          </div>
          <table id="table-layouts-<%= database.id %>" class="table" data-database-id="<%= database.id %>">
            <thead class="thead-light">
              <tr>
                <th>Task queue name</th>
                <th>Table</th>
                <th></th>
              </tr>
            </thead>
            <tbody class="table-borderless table-hover">
              <% @task_queues.select { |task_queue| task_queue.database_id == database.id }.each do |task_queue| %>
                <tr>
                  <td><%= task_queue.name %></td>
                  <td><%= task_queue.table.humanize %></td>
                  <td>
                    <%= link_to('Edit', edit_task_queue_path(task_queue.id), html_options = { class: "btn btn-primary btn-wide" }) %>
                  </td>
                </tr>
              <% end if @task_queues %>
            </tbody>
          </table>
          <br />
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/task_queues/index_old.html.erb
<div class="row">
  <div class="col-sm-12">
    <br>
    <div id="builder"></div>
    <br>
    <h3>Query Builder Rules</h3>
    <textarea name="" class="qb-rules form-control" id="myTextarea"></textarea>
    <br>
    <button id="btn-get" type="button" name="button" class="btn btn-success">Show rules</button>
    <button type="button" name="button" class="btn btn-success">Save</button>
    <br>
  </div>
</div>

<div class="modal fade" id="new-task-queue-modal" tabindex="-1" role="dialog" aria-labelledby="new-task-queue-modal">
  <div class="modal-dialog" role="document">
    <%= render partial: 'task_queues/new/new_queue_modal_screen_1' %>
    <%= render partial: 'task_queues/new/new_queue_modal_screen_2' %>
  </div>
</div>

app/views/task_queues/new.html.erb
<div class="row">
  <div class="col-sm-12">
  </div>
</div>

<div class="modal fade" id="new-task-queue-modal" tabindex="-1" role="dialog" aria-labelledby="new-task-queue-modal">
  <div class="modal-dialog" role="document">
    <%# <%= render partial: 'task_queues/new/new_queue_modal_screen_1' %>
    <%= render partial: 'task_queues/new/new_queue_modal_screen_2' %>
  </div>
</div>

app/views/task_queues/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'dataTable/datatables.min.js' %>
<% end %>

<%= render 'shared/page_banner_header', title: @task_queue.name.capitalize, items: ['Task Queue', @task_queue.name.capitalize] %>

<div class="wrapper wrapper-content animated ">
  <div class="row">
    <div class="col-sm-12">
      <h2><%= @task_queue.details %></h2>
    </div>
    <div class="col-sm-12">
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-12">
            <table id="target-table-task-queues" class="table hide" data-table-name="<%= @task_queue.table %>" data-database-id="<%= @task_queue.database_id %>" data-can-export="<%= current_admin_user.export_abilities? %>">
              <thead>
                <tr>
                  <% @headers.each do |header| %>
                    <th class='column-<%= header %>'><%= header.humanize %></th>
                  <% end %>
                </tr>
              </thead>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>