config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for(
    :admin_users,
    controllers: {
      registrations: 'admin_user_registrations',
      sessions: 'admin_user_sessions'
    }
  )

  devise_scope :admin_user do
    # root to: "admin_user_registrations#new"
    root to: "dashboard#show"
  end

  resources :task_queues, only: %i[new index show create edit update] do
    member do
      post 'outcome'
      get 'record'
      get 'preview'
      get 'field_settings'
    end

    # get 'table_fields_with_type'
  end

  resources :tables, only: %i[index show]
  get 'tables/:table_name/:record_id', to: 'tables#preview', as: 'table_record_preview'
  get 'table/settings', to: 'tables#settings'
  post 'table/update_settings', to: 'tables#update_settings'
  get 'table/add_record', to: 'tables#add_record'
  get 'table/edit_record', to: 'tables#edit_record'
  post 'table/update_record', to: 'tables#update_record'
  post 'table/create_record', to: 'tables#create_record'
  post 'table/delete_record', to: 'tables#delete_record'

  patch 'table_field', to: 'tables#update_table_field', as: 'update_table_field'
  patch 'related_table_field', to: 'tables#update_related_table_field', as: 'update_related_table_field'

  # get 'layouts/table_fields_with_type', to: 'layout_builder#table_fields_with_type'
  resources :layout_builder, as: "layouts", path: 'layouts'
  get 'layouts/:id/preview', to: 'layout_builder#preview', as: 'layout_builder_preview'
  patch 'layouts/:id/related_tables', to: 'layout_builder#update_related_tables', as: 'update_related_tables'
  patch 'layouts/:id/related_tables/remove', to: 'layout_builder#remove_related_table', as: 'remove_related_table'

  # get 'view_builder/table_fields', to: 'view_builder#table_fields'
  # # get 'view_builder/view', to: 'view_builder#view_page'
  # get 'view_builder/retrieve_data', to: 'view_builder#retrieve_data'

  get 'users/edit', to: 'admin_users#edit'
  get 'users/:id', to: 'admin_users#show_modal'
  post 'admin_users/update_role', to: 'admin_users#update_role'
  post 'admin_users/update_status', to: 'admin_users#update_status'
  post 'admin_users/create_new', to: 'admin_users#create_new'
  patch 'admin_users/create_new', to: 'admin_users#update'
  delete 'users', to: 'admin_users#destroy'
  get 'users', to: 'admin_users#index'

  resources :databases
  get 'table_fields_with_type', to: 'databases#table_fields_with_type'
  get 'related_table_fields_with_type', to: 'databases#related_table_fields_with_type'


  # resources :view_builder
  resources :activities, only: %i[create index]
  post 'activities/create_js', to: 'activities#create_js'

  resources :organisation_settings, only: %i[edit update]
  resources :admin_users, only: %i[new]
  resources :permissions, only: :index

  post 'permissions/add_to_role', to: 'permissions#add_to_role', as: 'add_to_role'
  post 'permissions/remove_from_role', to: 'permissions#remove_from_role'
  post 'permissions/enable_all', to: 'permissions#enable_all'
  post 'permissions/disable_all', to: 'permissions#disable_all'

  resource :roles, only: %i[edit update]

  get 'dashboard', to: 'dashboard#show'
  post 'add-sql-filter', to: 'work_lists#add_sql_filter'
  post 'remove-sql-filter', to: 'work_lists#remove_sql_filter'
  post 'remove-work-list-outcome', to: 'work_lists#remove_work_list_outcome'
  post 'add-work-list-outcome', to: 'work_lists#add_work_list_outcome'

  post 'token/generate' => 'token#generate'
  post 'call/connect' => 'call#connect'

  get 'license', to: 'dashboard#license'
  post 'license/verify', to: 'dashboard#verify_license'
  get 'license/verify', to: 'dashboard#verify_license', as: 'verify_license'

  get 'data_table_states/load'
  post 'data_table_states/save'

  match "database_connection_error", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match '/404' => 'errors#not_found', via: :all
  match '/406' => 'errors#not_acceptable', via: :all
  match '/401' => "errors#not_authorized", via: :all
end

app/controllers/databases_controller.rb
# frozen_string_literal: true

class DatabasesController < ApplicationController
  include DatabaseActions
  include DatabasePresenterActions

  layout 'standard'

  before_action :check_user_permissions, only: %i[new edit]

  IGNORED_COLUMNS = %w[id created_at updated_at].freeze

  def index
    @databases = Database.all
    can_add = current_admin_user.admin_abilities? && params[:settings]
    json = { databases: @databases.sort, can_add: can_add }.to_json

    respond_to do |format|
      format.js { render json: json }
    end
  end

  def new
    @database = Database.new
  end

  def create
    @database = Database.new(database_params)
    create_database_actions
  end

  def edit
    @database = Database.find(params[:id])
  end

  def update
    @database = Database.find(params[:id])
    update_database_actions
  end

  def destroy
    database = Database.find(params[:id])
    database.delete
    redirect_to dashboard_path
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Something went wrong trying to delete this database. Please try again.'
    redirect_to(databases_path)
  end

  def table_fields_with_type
    @database = Database.find(params[:id])
    @database_connection = database_connection
    @fields_with_type = list_table_fields_with_type(params[:table])
    render json: @fields_with_type.sort
  end

  def related_table_fields_with_type
    @database = Database.find(params[:id])
    @database_connection = database_connection
    table = params[:table]
    related_tables = relatable_tables(table)
    table_fields_with_type = list_table_fields_with_type(table)
    all_fields_with_type = []
    table_fields_with_type.each { |field| all_fields_with_type << field }
    related_tables.each do |related_table|
      list_related_table_fields_with_type(related_table).each { |field| all_fields_with_type << field }
    end
    render json: all_fields_with_type
  end

  private

  def check_user_permissions
    return if current_admin_user.admin_abilities?

    flash[:alert] = 'You do not have sufficient permissions to manage database settings'
    redirect_to(dashboard_path)
  end

  def database_params
    params.require(:database).permit(:friendly_name,
                                     :adapter,
                                     :host,
                                     :port,
                                     :name,
                                     :password,
                                     :username)
  end

  def database_params_update
    permitted = params.require(:database).permit(:friendly_name,
                                                 :adapter,
                                                 :host,
                                                 :port,
                                                 :name,
                                                 :username,
                                                 :domain_url,
                                                 :gem_token)

    permitted.merge!(password: params[:database][:password]) if params[:database][:password_changed] == 'true'
    permitted
  end

  def password_param
    params[:database][:password]
  end
end

app/views/databases/_credentials_form.html.erb
<%= form_for(@database, remote: true) do |f| %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :friendly_name %>
        <%= f.text_field :friendly_name, autofocus: true, class: "form-control", placeholder: "Enter database name" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :adapter %>
        <%= f.select(:adapter, Database::DATABASE_TYPES,
                                            {prompt: "Please select"},
                                            {class: 'form-control'}) %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :host %>
        <%= f.text_field :host, autofocus: true, class: "form-control", required: true %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, autofocus: true, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :port %>
        <%= f.number_field :port, autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, autofocus: true, class: "form-control", value: @database.password %>
        <%= f.hidden_field :password_changed, value: false %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-11">
      <%= f.submit "Test connection", class: "btn btn-primary m-b pull-right", id: "test-database-connection" %>
      <% if @database.persisted? %>
        <%= link_to "Remove database", database_path(@database), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger m-b pull-right margin-right" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <h4>Don't forget to <%= link_to "set the database permissions here", permissions_path %>, otherwise you won't be able to see any tables.</h4>
    </div>
    <div class="col-sm-3">
      <%= f.submit "Save", class: "btn btn-primary m-b pull-right" %>
    </div>
  </div>
<% end %>

app/views/databases/_mission_kontrol_relay_form.html.erb
<%= form_for(@database, remote: true) do |f| %>
  <div class="row flex">
    <div class="col-sm-4">
      <h2 class="medium">MissionKontrolRelay Gem</h2>
      <h4>MissionKontrolRelay is ruby gem you can install on an application related to your database.</h4>
      <br>
      <h4>The token required for the connection will be created when you install the gem.</h4>
      <br>
      <h4>Find more information <a href="https://www.rubydoc.info/gems/mission_kontrol_relay/">here</a>
    </div>
     <div class="col-sm-8 align-self-center">
      <div class="form-group">
        <%= f.label :domain_url %>
        <%= f.text_field :domain_url, autofocus: true, class: "form-control", placeholder: "" %>
      </div>
      <div class="form-group">
        <%= f.label :gem_token %>
        <%= f.text_field :gem_token, autofocus: true, class: "form-control", placeholder: "" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-11">
      <%= f.submit "Test gem", class: "btn btn-primary m-b pull-right", id: "test-gem-connection" %>
      <% if @database.persisted? %>
        <%= f.submit "Remove gem", class: "btn btn-danger m-b pull-right margin-right", id: "remove-gem-connection", data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
    </div>
    <div class="col-sm-3">
      <%= f.submit "Save", class: "btn btn-primary m-b pull-right" %>
    </div>
  </div>
<% end %>

app/views/databases/_tabs.html.erb
<div class="wrapper wrapper-content animated">
  <div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-12">
          <div class="tabs-container">
            <ul class="nav nav-tabs" role="tablist">
              <li class="active"><a class="nav-link active" data-toggle="tab" href="#settings-tab--general">General</a></li>
              <% if @database.persisted? %>
                <li><a class="nav-link" data-toggle="tab" href="#settings-tab--mkr">MissionKontrolRelay</a></li>
              <% end %>
            </ul>
            <div class="tab-content">
              <div role="tabpanel" id="settings-tab--general" class="tab-pane active">
                <div class="panel-body">
                  <%= render 'credentials_form' %>
                </div>
              </div>
              <div role="tabpanel" id="settings-tab--mkr" class="tab-pane">
                <div class="panel-body">
                  <%= render 'mission_kontrol_relay_form' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/databases/create.js.erb
<% if @result %>
  window.location.assign('/permissions');
  toastr.success('Database has been successfully created.')
<% else %>
  toastr.error('Unable to save database. Please check your credentials and try again.');
<% end %>

app/views/databases/edit.html.erb
<%= render 'shared/page_banner_header', title: 'Settings', items: ['Settings', 'Databases', "#{@database.friendly_name}"] %>

<%= render 'tabs' %>

app/views/databases/new.html.erb
<%= render 'shared/page_banner_header', title: 'Settings', items: ['Settings', 'Databases'] %>

<%= render 'tabs' %>

app/views/databases/test_connection.js.erb
<% if @active_connection %>
  toastr.success('Database connection successful.')
<% else %>
  toastr.error('Unable to connect to database. Please check your credentials and try again.');
<% end %>

app/views/databases/test_gem.js.erb
<% if @active_gem_connection %>
  toastr.success('Gem connection successful.')
<% else %>
  toastr.error('Unable to connect to your application. Please check your credentials and try again.');
<% end %>

app/views/databases/update.js.erb
<% if @result %>
  toastr.success("<%= t('successes.has_been_successfully_updated', model: 'Database') %>");
<% else %>
  toastr.error("<%= t('errors.unable_to_save', model: 'database') %>");
<% end %>