config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for(
    :admin_users,
    controllers: {
      registrations: 'admin_user_registrations',
      sessions: 'admin_user_sessions'
    }
  )

  devise_scope :admin_user do
    # root to: "admin_user_registrations#new"
    root to: "dashboard#show"
  end

  resources :task_queues, only: %i[new index show create edit update] do
    member do
      post 'outcome'
      get 'record'
      get 'preview'
      get 'field_settings'
    end

    # get 'table_fields_with_type'
  end

  resources :tables, only: %i[index show]
  get 'tables/:table_name/:record_id', to: 'tables#preview', as: 'table_record_preview'
  get 'table/settings', to: 'tables#settings'
  post 'table/update_settings', to: 'tables#update_settings'
  get 'table/add_record', to: 'tables#add_record'
  get 'table/edit_record', to: 'tables#edit_record'
  post 'table/update_record', to: 'tables#update_record'
  post 'table/create_record', to: 'tables#create_record'
  post 'table/delete_record', to: 'tables#delete_record'

  patch 'table_field', to: 'tables#update_table_field', as: 'update_table_field'
  patch 'related_table_field', to: 'tables#update_related_table_field', as: 'update_related_table_field'

  # get 'layouts/table_fields_with_type', to: 'layout_builder#table_fields_with_type'
  resources :layout_builder, as: "layouts", path: 'layouts'
  get 'layouts/:id/preview', to: 'layout_builder#preview', as: 'layout_builder_preview'
  patch 'layouts/:id/related_tables', to: 'layout_builder#update_related_tables', as: 'update_related_tables'
  patch 'layouts/:id/related_tables/remove', to: 'layout_builder#remove_related_table', as: 'remove_related_table'

  # get 'view_builder/table_fields', to: 'view_builder#table_fields'
  # # get 'view_builder/view', to: 'view_builder#view_page'
  # get 'view_builder/retrieve_data', to: 'view_builder#retrieve_data'

  get 'users/edit', to: 'admin_users#edit'
  get 'users/:id', to: 'admin_users#show_modal'
  post 'admin_users/update_role', to: 'admin_users#update_role'
  post 'admin_users/update_status', to: 'admin_users#update_status'
  post 'admin_users/create_new', to: 'admin_users#create_new'
  patch 'admin_users/create_new', to: 'admin_users#update'
  delete 'users', to: 'admin_users#destroy'
  get 'users', to: 'admin_users#index'

  resources :databases
  get 'table_fields_with_type', to: 'databases#table_fields_with_type'
  get 'related_table_fields_with_type', to: 'databases#related_table_fields_with_type'


  # resources :view_builder
  resources :activities, only: %i[create index]
  post 'activities/create_js', to: 'activities#create_js'

  resources :organisation_settings, only: %i[edit update]
  resources :admin_users, only: %i[new]
  resources :permissions, only: :index

  post 'permissions/add_to_role', to: 'permissions#add_to_role', as: 'add_to_role'
  post 'permissions/remove_from_role', to: 'permissions#remove_from_role'
  post 'permissions/enable_all', to: 'permissions#enable_all'
  post 'permissions/disable_all', to: 'permissions#disable_all'

  resource :roles, only: %i[edit update]

  get 'dashboard', to: 'dashboard#show'
  post 'add-sql-filter', to: 'work_lists#add_sql_filter'
  post 'remove-sql-filter', to: 'work_lists#remove_sql_filter'
  post 'remove-work-list-outcome', to: 'work_lists#remove_work_list_outcome'
  post 'add-work-list-outcome', to: 'work_lists#add_work_list_outcome'

  post 'token/generate' => 'token#generate'
  post 'call/connect' => 'call#connect'

  get 'license', to: 'dashboard#license'
  post 'license/verify', to: 'dashboard#verify_license'
  get 'license/verify', to: 'dashboard#verify_license', as: 'verify_license'

  get 'data_table_states/load'
  post 'data_table_states/save'

  match "database_connection_error", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match '/404' => 'errors#not_found', via: :all
  match '/406' => 'errors#not_acceptable', via: :all
  match '/401' => "errors#not_authorized", via: :all
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  KINDS = %w[note call meeting outcome].freeze
  ## TODO: Figure out the feedable_types based on database?
  # FEEDABLE_TYPES = Kuwinda::Presenter::ListAvailableTables.new(@database_connection).call

  validates :content, presence: true
  validates :kind, presence: true, inclusion: { in: KINDS }
  validates :feedable_id, presence: true

  belongs_to :admin_user, class_name: 'AdminUser', foreign_key: 'user_id'
  # validates :feedable_type, presence: true, inclusion: { in: FEEDABLE_TYPES }
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

class ActivitiesController < ApplicationController
  include TableActivity

  layout 'standard'

  before_action :set_activities, only: :index

  def create
    @activity = Activity.new(activity_params.except(:twilio_call_sid))

    respond_to do |format|
      if @activity.save
        format.js { render action: 'success' }
      else
        format.js { render action: 'failure', status: :unprocessable_entity }
      end
    end
  end

  def create_js
    @activity = Activity.new(js_activity_params)

    respond_to do |format|
      if @activity.save
        json = {
          activity: @activity,
          created_at: @activity.created_at.strftime('%a, %d %b %Y at %I:%M'),
          user_name: @activity.admin_user.full_name
        }
        format.js { render action: 'success', json: json }
      else
        format.js { render action: 'failure', status: :unprocessable_entity }
      end
    end
  end

  def index
    @activity = Activity.new
    @database_id = params[:database_id]
    @feedable_type = params[:feedable_type]
    @feedable_id = params[:feedable_id]
    @activities_for_table = Activity.where(
      feedable_type: @feedable_type,
      feedable_id: @feedable_id
    ).sort_by(&:created_at).reverse

    group_activities_by_kind
  end

  private

  def activity_params
    params.require(:activity).permit(:content,
                                     :kind,
                                     :feedable_type,
                                     :feedable_id,
                                     :user_id,
                                     :database_id,
                                     :twilio_call_sid)
  end

  def js_activity_params
    params.permit(:content,
                  :kind,
                  :feedable_type,
                  :feedable_id,
                  :database_id,
                  :user_id)
  end
end

app/helpers/activity_helper.rb
# frozen_string_literal: true

module ActivityHelper
  def render_activity(activity)
    name = activity.admin_user == current_admin_user ? 'You' : activity.admin_user.full_name
    case activity.kind
    when 'note'
      content_tag(:strong, name) +
        content_tag(:span, ' added a ') +
        content_tag(:strong, 'comment: ') +
        content_tag(:span, activity.content.to_s)
    when 'outcome'
      content_tag(:strong, name) +
        content_tag(:span, ' added a ') +
        content_tag(:strong, 'tag: ') +
        content_tag(:span, activity.content.to_s)
    end
  end
end

app/views/activities/_activity.html.erb
<tr>
  <td>
    <%= activity.created_at.strftime('%a, %d %b %Y at %I:%M') %>
  </td>
  <td>
    <%= render_activity(activity) %>
    <% if locals[:link] %>
      <span>to a <%= link_to "record", table_record_preview_path(table: activity.feedable_type, table_name: activity.feedable_type, record_id: activity.feedable_id, database_id: activity.database_id) %> on <%= link_to activity.feedable_type, table_path(id: activity.database_id, table: activity.feedable_type) %> table</span>
    <% end %>
  </td>
</tr>

app/views/activities/_form.html.erb
<div>
  <%= form_with(model: @activity, local: false, data: { 'activity-form' => true }, class: 'activity-comment-form') do |form| %>
    <%= form.hidden_field :feedable_type, id: :feedable_type, value: feedable_type  %>
    <%= form.hidden_field :feedable_id, id: :feedable_id, value: feedable_id  %>
    <%= form.hidden_field :database_id, value: @database.id %>
    <%= form.hidden_field :kind, value: 'note'  %>
    <%= form.hidden_field :user_id, value: current_admin_user.id %>


    <%= form.text_field :content, placeholder: 'Click to add a comment', class: "activity-comment-form--input" %>
    <%= form.submit 'Submit', class: 'btn btn-info btn-middle-align btn-square' %>
  <% end %>
</div>

app/views/activities/_task_queue_record_activity_form.html.erb
<div>
  <%= form_with(model: @activity, local: false, scope: 'activity', html: { id: 'task-queue-record-activity-form' }, url: activities_path) do |form| %>
    <div class="form-group">
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.hidden_field :feedable_type, id: :feedable_type, value: feedable_type  %>
      <%= form.hidden_field :kind, value: 'note'  %>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="actions text-right">
          <%= form.submit 'Save', class: 'btn btn-primary', id: 'task-queue-record-activity-submit' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/activities/failure.js.erb
toastr.error('Failed to save activity.');

app/views/activities/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h1>Activity history</h1>

    <ol class="breadcrumb">
      <li class="">
        <%= link_to @feedable_type.humanize, table_path(table: @feedable_type, id: @feedable_type.downcase) %>
      </li>

      <li class="">
        <%= link_to @feedable_id, table_record_preview_path(table: @feedable_type, table_name: @feedable_type, record_id: @feedable_id, database_id: @database_id) %>
      </li>
    </ol>
  </div>
</div>

<div class="panel-body">
  <div class="row">
    <div class="col-sm-12">
      <%= render 'shared/activity_history', feedable_type: @feedable_type, feedable_id: @feedable_id, index: true %>
    </div>
  </div>
</div>

app/views/activities/success.js.erb
<%# ## TODO: if first comment or activity on record add table? %>
if ($(".all-activities-tab").find("table > tbody > tr").length === 3) {
  $(".all-activities-tab").find("table > tbody > tr:last").remove();
}

$(".all-activities-tab").find(".activities-history--table").prepend("<%= j render @activity, locals: { link: false } %>");
$('.all-activities-tab .default-message').remove();

if ("<%= @activity.kind %>" === "note") {
  if ($(".activity-tab-for-notes").find("table > tbody > tr").length === 3) {
    $(".activity-tab-for-notes").find("table > tbody > tr:last").remove();
  }

  $(".activity-tab-for-notes").find(".activities-history--table").prepend("<%= j render @activity, locals: { link: false } %>");
  $('.activity-tab-for-notes .default-message').remove();
}

if ("<%= @activity.kind %>" === "outcome") {
  if ($(".activity-tab-for-outcomes").find("table > tbody > tr").length === 3) {
    $(".activity-tab-for-outcomes").find("table > tbody > tr:last").remove();
  }

  $(".activity-tab-for-outcomes").find(".activities-history--table").prepend("<%= j render @activity, locals: { link: false } %>");
  $('.activity-tab-for-outcomes .default-message').remove();
}

if ("<%= @activity.kind %>" === "call") {
  $(".activity-tab-for-calls .activity-stream").prepend("<%= j render @activity, locals: { link: false } %>");
  $('.activity-tab-for-calls .default-message').remove();
}

if ("<%= @activity.kind %>" === "meeting") {
  $(".activity-tab-for-meetings .activity-stream").prepend("<%= j render @activity, locals: { link: false } %>");
  $('.activity-tab-for-meetings .default-message').remove();
}

toastr.success('Activity was successfully created.');
$('.all-activities-tab').find('.activity-comment-form--input').val('');
$('.activity-tab-for-notes').find('.activity-comment-form--input').val('');